# Generated by InFoundry with Kestra AI Agent — AZURE
# Timestamp: 2026-03-22T02:49:58.790155
# Pattern: microservices_ecs
# Source: heuristic

# Skipped: no template for 'ecs_cluster' on azure

# Skipped: no template for 'rds' on azure

# Skipped: no template for 'alb' on azure
