import os
import re
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from dotenv import load_dotenv

from langchain_groq import ChatGroq
from langgraph.prebuilt import create_react_agent

from agent_tools import get_wallet_balance, trigger_guardian_payment, execute_arbitrage_scan

load_dotenv()

app = FastAPI(title="AlgoAgentX API")

# CORS — allow development frontend
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Initialize LLM using native ChatGroq — reads GROQ_API_KEY from environment automatically
llm = ChatGroq(model="llama-3.3-70b-versatile", temperature=0)

# Tools list
tools = [get_wallet_balance, trigger_guardian_payment, execute_arbitrage_scan]

# Initialize agent via LangGraph with a system prompt modifier
system_prompt = (
    "You are an Algorand Agent with access to LocalNet and Mainnet tools. "
    "Your address is RWBBCDFWI6PTEFCQPVGR3P7RC2K55HGZ23PZEWU656TWYK6OBU4IPFCEHQ. "
    "Use your tools to help users. Always use your tools to perform actions like checking balances, making payments, "
    "or performing arbitrage scans when requested."
)
agent_executor = create_react_agent(llm, tools, prompt=system_prompt)

class ChatRequest(BaseModel):
    prompt: str

@app.post("/api/chat")
async def chat_endpoint(req: ChatRequest):
    try:
        # LangGraph invoke expects a dict with messages
        response = agent_executor.invoke({"messages": [("user", req.prompt)]})
        # The last message typically contains the agent's textual response
        messages = response.get("messages", [])
        output_text = messages[-1].content if messages else ""
        if isinstance(output_text, list):
            output_text = str(output_text)
        
        # Extract potential TX IDs generated by our tool output
        tx_ids = re.findall(r'TX:\s*([A-Za-z0-9A-Z]{52})', output_text)
        
        if not tx_ids:
             tx_ids = re.findall(r'TX:\s*([A-Za-z0-9]+)', output_text)

        return {
            "response": output_text,
            "tx_ids": tx_ids
        }
    except Exception as e:
        return {"response": f"Error interacting with agent: {str(e)}", "tx_ids": []}

if __name__ == "__main__":
    import uvicorn
    uvicorn.run("main:app", host="0.0.0.0", port=8000, reload=True)
