# Generated by InFoundry with Kestra AI Agent — GCP
# Timestamp: 2026-03-22T02:47:47.138177
# Pattern: microservices_ecs
# Source: heuristic

# Skipped: no template for 'ecs_cluster' on gcp

# Skipped: no template for 'rds' on gcp

# Skipped: no template for 'alb' on gcp
