# Generated by InFoundry with Kestra AI Agent — GCP
# Timestamp: 2026-03-22T03:07:04.933462
# Pattern: microservices_ecs
# Source: heuristic

resource "google_cloud_run_v2_service" "cloud_run" {
      name     = "${var.project_name}-cloud_run"
      location = var.region
      project  = var.project_id
      template {
        containers {
          image = "gcr.io/${var.project_id}/${var.project_name}:latest"
          resources {
            limits = {
              cpu    = "1000m"
              memory = "512Mi"
            }
          }
          env {
            name  = "ENVIRONMENT"
            value = var.environment
          }
        }
        scaling {
          min_instance_count = 0
          max_instance_count = 10
        }
      }
    }

    resource "google_cloud_run_v2_service_iam_member" "cloud_run_public" {
      project  = var.project_id
      location = var.region
      name     = google_cloud_run_v2_service.cloud_run.name
      role     = "roles/run.invoker"
      member   = "allUsers"
    }
    

resource "google_sql_database_instance" "cloud_sql" {
      name             = "${var.project_name}-cloud_sql"
      database_version = "POSTGRES_15"
      region           = var.region
      project          = var.project_id
      settings {
        tier = "db-f1-micro"
        backup_configuration {
          enabled = true
        }
        ip_configuration {
          ipv4_enabled = false
          require_ssl  = true
        }
      }
      deletion_protection = false
    }

    resource "google_sql_database" "cloud_sql_db" {
      name     = replace(var.project_name, "-", "_")
      instance = google_sql_database_instance.cloud_sql.name
      project  = var.project_id
    }

    resource "google_sql_user" "cloud_sql_user" {
      name     = "appuser"
      instance = google_sql_database_instance.cloud_sql.name
      password = local.db_password
      project  = var.project_id
    }
    

resource "google_compute_backend_service" "cloud_load_balancer" {
      name    = "${var.project_name}-cloud_load_balancer"
      project = var.project_id
    }
    
